version: "3"

services:
    app:
        build: .
        container_name: keycloak
        environment: 
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_ADDR=db
            - DB_VENDOR=mysql
            - DB_DATABASE=keycloak
            - DB_PORT=3306
            - DB_USER=dev
            - DB_PASSWORD=dev
        volumes: 
            - ./my_template:/opt/jboss/keycloak/themes/my_template
        ports: 
            - 8080:8080
        depends_on:
            - db
    
    db:
        image: mysql
        container_name: keycloak_mysql
        restart: always
        tty: true
        ports:
            - 3306:3306
        volumes: 
            - ./.docker/dbdata:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
            - MYSQL_DATABASE=keycloak